from langgraph.graph import END, START, StateGraph

from email_sender import send_email
from state import State
from tools import fetch_latest_india_news, summarize_article, today_string


def fetch_news_node(state: State) -> dict:
    return {"articles": fetch_latest_india_news()}


def summarize_news_node(state: State) -> dict:
    summaries = []
    for article in state.get("articles", []):
        summaries.append(summarize_article(article))
    return {"summaries": summaries}


def create_email_node(state: State) -> dict:
    articles = state.get("articles", [])
    summaries = state.get("summaries", [])

    html_parts = [
        '<div style="font-family:Arial;padding:20px;background:#f5f7fa;">',
        '  <div style="max-width:700px;margin:auto;background:white;padding:30px;border-radius:12px;">',
        f'    <h1 style="color:#2563eb;">📰 Daily AI News Brief - {today_string()}</h1>',
        '    <p>Good Morning! 👋</p>',
        '    <h2>🚀 Top Headlines</h2>',
    ]

    colors = ["#2563eb", "#10b981", "#f59e0b", "#ef4444", "#8b5cf6"]
    for index, article in enumerate(articles):
        summary = summaries[index] if index < len(summaries) else "No summary available."
        color = colors[index % len(colors)]
        html_parts.extend([
            f'    <div style="border-left:4px solid {color};padding-left:15px;margin-bottom:20px;">',
            f'      <h3>{article.get("title", "Untitled article")}</h3>',
            f'      <p>{summary}</p>',
            f'      <p><a href="{article.get("url", "")}" style="color:#2563eb;">Read more →</a></p>',
            '    </div>',
        ])

    html_parts.extend([
        '    <hr>',
        '    <p style="color:gray;">',
        '      Generated by AI News Agent • Every day at 07:30 AM',
        '    </p>',
        '  </div>',
        '</div>',
    ])

    return {"email": "\n".join(html_parts)}


def send_email_node(state: State) -> dict:
    subject = f"Daily AI News Digest - {today_string()}"
    send_email(subject=subject, body=state.get("email", ""), is_html=True)
    return {}


def build_graph():
    graph = StateGraph(State)
    graph.add_node("fetch_news", fetch_news_node)
    graph.add_node("summarize_news", summarize_news_node)
    graph.add_node("create_email", create_email_node)
    graph.add_node("send_email", send_email_node)

    graph.add_edge(START, "fetch_news")
    graph.add_edge("fetch_news", "summarize_news")
    graph.add_edge("summarize_news", "create_email")
    graph.add_edge("create_email", "send_email")
    graph.add_edge("send_email", END)
    return graph.compile()


app = build_graph()
